### ISSUE TITLE
Add audio transcription via Whisper

### ISSUE THREAD

**Issue by AtlantisPleb** [OpenAgentsInc/openagents#665]
Add a new CLI tool for transcribing audio files using Groq's Whisper API.

### Requirements

- Create new binary `src/bin/transcribe.rs`
- Use `whisper-large-v3` model for highest accuracy
- Load `GROQ_API_KEY` from `.env` file using dotenvy
- Save transcripts to `docs/transcripts/{timestamp}.md`
- Support local audio file input
- Use 'text' response format

### Implementation Details

1. Add new dependencies to Cargo.toml:
```toml
[dependencies]
groq = "0.1"  # Groq API client
dotenvy = "0.15"  # Already installed
chrono = "0.4"  # For timestamps
```

2. Create new binary that:
- Takes audio file path as command line argument
- Loads GROQ_API_KEY from .env
- Validates file exists and is supported format (flac, mp3, mp4, mpeg, mpga, m4a, ogg, wav, webm)
- Makes API call to Groq transcription endpoint:
  ```
  POST https://api.groq.com/openai/v1/audio/transcriptions
  ```
  With parameters:
  - model: "whisper-large-v3"
  - response_format: "text"
  - file: (binary file data)

3. Save response to `docs/transcripts/{timestamp}.md` with metadata header:
```md
---
source_file: {original filename}
timestamp: {ISO timestamp}
model: whisper-large-v3
---

{transcription text}
```

### Usage Example
```bash
cargo run --bin transcribe path/to/audio.mp3
```

### Error Handling
- Check file exists and is valid format
- Validate GROQ_API_KEY is set
- Handle API errors gracefully
- Create transcripts directory if it doesn't exist

### Testing
- Add tests for:
  - File validation
  - API error handling
  - Output file creation
  - Environment loading

**Comment by AtlantisPleb** [comment]
Additional requirement: Add video support

For .mp4 video files:
1. Extract audio track using ffmpeg before sending to Groq API
2. Convert to a supported audio format (preferably FLAC for lossless quality)
3. Use ffmpeg command similar to:
```bash
ffmpeg -i input.mp4 -vn -acodec flac -ar 16000 -ac 1 output.flac
```

This will:
- `-vn`: Skip video track
- `-acodec flac`: Use FLAC codec
- `-ar 16000`: Set sample rate to 16kHz (optimal for Whisper)
- `-ac 1`: Convert to mono

Add `ffmpeg-next` crate as dependency for handling the conversion.

(Comment from OpenAgents)

**Comment by AtlantisPleb** [comment]
Update on dependencies:

We don't need the `groq` crate - we can just use the raw HTTP API with `reqwest`. The endpoint is a simple multipart form POST request to:
```
https://api.groq.com/openai/v1/audio/transcriptions
```

Updated dependencies needed:
```toml
[dependencies]
reqwest = { version = "0.11", features = ["multipart"] }  # For HTTP API calls
dotenvy = "0.15"  # Already installed
chrono = "0.4"  # For timestamps
ffmpeg-next = "6.1"  # For video/audio processing
tokio = { version = "1", features = ["full"] }  # For async runtime
```

Example request structure:
```rust
let form = reqwest::multipart::Form::new()
    .text("model", "whisper-large-v3")
    .text("response_format", "text")
    .file("file", "path/to/audio.flac")?;

let client = reqwest::Client::new();
let response = client
    .post("https://api.groq.com/openai/v1/audio/transcriptions")
    .header("Authorization", format!("Bearer {}", groq_api_key))
    .multipart(form)
    .send()
    .await?;

(Comment from OpenAgents)
