### ISSUE TITLE
Add Ollama connection status indicator to Pylon dashboard

### ISSUE THREAD

**Issue by AtlantisPleb** [OpenAgentsInc/openagents#924]
### Summary
Add a visual indicator to the Pylon dashboard that shows whether a local Ollama instance is running and accessible.

### Description
The Pylon dashboard should display a connection status indicator for local Ollama instances. This will help users quickly verify if their local Ollama server is running and accessible before attempting to use it.

#### Visual Design
- Add a status card below the main "Pylon" title card
- Display a colored dot indicator:
  - 🟢 Green dot: Ollama is online and accessible
  - 🔴 Red dot: Ollama is offline or unreachable
- Include text showing "Ollama: Online" or "Ollama: Offline"

#### Technical Approach
1. **Health Check Endpoint**: Use `GET http://localhost:11434/api/tags` to check Ollama status
   - This endpoint returns available models without requiring a model to be loaded
   - Alternative: Use root endpoint `GET http://localhost:11434/` for a simpler check

2. **Effect Integration**: Implement using Effect framework for consistency with SDK
   ```typescript
   const checkOllamaStatus = Effect.tryPromise({
     try: () => fetch('http://localhost:11434/api/tags'),
     catch: () => new OllamaConnectionError()
   })
   ```

3. **Polling**: Check status on page load and optionally poll every 5-10 seconds

4. **CORS Handling**: May need to handle CORS if Ollama doesn't allow browser requests

#### UI Structure
```html
<div class="webtui-box webtui-box-single ollama-status-card">
  <div class="status-indicator">
    <span class="status-dot"></span>
    <span class="status-text">Ollama: Checking...</span>
  </div>
</div>
```

#### Styling (using WebTUI variables)
```css
.ollama-status-card {
  margin-top: 1rem;
  padding: 1rem 2rem;
}

.status-dot {
  display: inline-block;
  width: 12px;
  height: 12px;
  border-radius: 50%;
  margin-right: 0.5rem;
}

.status-dot.online {
  background-color: var(--webtui-green);
}

.status-dot.offline {
  background-color: var(--webtui-red);
}
```

### Benefits
- Immediate visual feedback about Ollama availability
- Helps troubleshoot connection issues
- Improves user experience by preventing failed API calls
- Consistent with WebTUI design system

### Related Context
- Ollama runs on default port 11434
- Previous Ollama integration work in #642
- Pylon uses Effect framework and WebTUI for styling
